### ISSUE TITLE
Message : A section with name "X" could not be found.

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#1435]
When I go into page edit mode my log gets slammed with a lot of 

Message : A section with name "head" could not be found.
Message : A section with name "top" could not be found.
...

errors, those sections very clearly do exist in my layout thought

**Comment by manev** [comment]
Hi Steve,
Can you point the the widget where we can observe this behavior or is this is a custom widget?

**Comment by sitefinitysteve** [comment]
If you just go into VS debug on the root Feather project, then enter page edit mode (I think after a build or fresh iis recycle) visual studio will trip the exception.  You see NOTHING on the front end, but shows up in the log file.

**Comment by sitefinitysteve** [comment]
Here's the log exception

Message: HandlingInstanceID: b01cd793-8634-4d51-99d9-461b50b3f7cc
An exception of type 'System.ArgumentException' occurred and was caught.
------------------------------------------------------------------------
04/28/2015 11:28:34
Type : System.ArgumentException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : A section with name "top" could not be found.
Parameter name: top
Source : Telerik.Sitefinity.Frontend
Help link : 
ParamName : top
Data : System.Collections.ListDictionaryInternal
TargetSite : Boolean Register(System.String, System.String, Boolean)
HResult : -2147024809
Stack Trace :    at Telerik.Sitefinity.Frontend.Resources.ResourceRegister.Register(String resourceKey, String sectionName, Boolean throwException)
   at Telerik.Sitefinity.Frontend.Mvc.Helpers.ResourceHelper.RegisterResource(HttpContextBase httpContext, String resourcePath, ResourceType resourceType, String sectionName, Boolean throwException)
   at Telerik.Sitefinity.Frontend.Mvc.Helpers.ResourceHelper.Script(HtmlHelper helper, ScriptRef scriptReference, String sectionName, Boolean throwException)
   at Telerik.Sitefinity.Frontend.Mvc.Helpers.ResourceHelper.Script(HtmlHelper helper, ScriptRef scriptReference, String sectionName)
   at ASP._Page_Frontend_Assembly_Telerik_Sitefinity_Frontend_Identity_Mvc_Views_Profile_Edit_ProfileEdit_cshtml_OutbreakHelp_cshtml.Execute() in c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\5903706b\9cbd7e3a\App_Web_edit.profileedit.cshtml#outbreakhelp.cshtml.bdf41b90.-voci8n-.0.cs:line 0
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<InvokeActionResultWithFilters>b__17()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass1a.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
   at Telerik.Sitefinity.Mvc.ControllerWrapper.Execute()
   at Telerik.Sitefinity.Mvc.ControllerActionInvoker.ExecuteController(MvcProxyBase proxyControl)
   at Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Routing.DynamicUrlParamActionInvoker.ExecuteController(MvcProxyBase proxyControl)

**Comment by Boyko-Karadzhov** [comment]
Hello Steve,

There was indeed a bug there. The fix will most probably be included in the next release. It is in for testing.

Regards,
Boyko

**Comment by M-Yankov** [comment]
I followed this article  [Feather create layout files](http://docs.sitefinity.com/feather-create-layout-files) and received the same error message. But in my case sections are missing. So just adding `@Html.Section("head")` in my layout resolved the problems.  
I hope this can help to someone.

**Comment by assainov** [comment]
> So just adding `@Html.Section("head")` in my layout resolved the problems.
> I hope this can help to someone.
You saved my day!
