### ISSUE TITLE
Cannot find template "~/Frontend-Assembly/Telerik.Sitefinity.Frontend/GridSystem/Templates/container-white.html".

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#1595]
I'm using a webforms page for login (STS), and when I try to add a custom feather layout (drop a new cshtml into GridSystem/Templates) the page designer throws an exception on the layout, and my log file gets this...

Timestamp: 5/6/2015 3:46:31 PM

Message: HandlingInstanceID: 2bcfd115-f130-4d59-aeaf-485fd274559a
An exception of type 'System.ArgumentException' occurred and was caught.
------------------------------------------------------------------------
05/06/2015 11:46:31
Type : System.ArgumentException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : Cannot find template "~/Frontend-Assembly/Telerik.Sitefinity.Frontend/GridSystem/Templates/container-white.html".
Source : Telerik.Sitefinity.Frontend
Help link : 
ParamName : 
Data : System.Collections.ListDictionaryInternal
TargetSite : System.Web.UI.ITemplate GetTemplate(Boolean, Boolean, System.String)
HResult : -2147024809
Stack Trace :    at Telerik.Sitefinity.Frontend.GridSystem.GridControl.GetTemplate(Boolean isVirtualPath, Boolean isHtmlTemplate, String layout)
   at Telerik.Sitefinity.Frontend.GridSystem.GridControl.GetTemplate()
   at Telerik.Sitefinity.Web.UI.LayoutControl.Initialize()
   at Telerik.Sitefinity.Web.UI.LayoutControl.CreateChildControls()

Additional Info:

MachineName : CLOUD-SERVER-03
TimeStamp : 5/6/2015 3:46:31 PM
FullName : Telerik.Sitefinity.Utilities, Version=8.0.5704.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/2/ROOT-1-130753248092484173
ThreadIdentity : admin

Steve

**Comment by Boyko-Karadzhov** [comment]
Hello Steve,

Grid widgets are registered per package. You will get that message if the page where the grid widget is dropped is not based on a template from the corresponding package.

Would check whether the page where you get the exception is based on a page template from the package where _container-white.html_ is placed?

Regards,
Boyko

**Comment by sitefinitysteve** [comment]
Yeah its definitely not, it's webforms based...so those should just outright not be showing up then eh? ...or could there be a way where I could remove the relative path and make it fixed.

**Comment by Boyko-Karadzhov** [comment]
You have several options:

- make the page use the resource package by basing it on a page template that is named following the convention _[package name].[whatever name you choose for the template]_. That template could be WebForms. Packages should still work.
- copy the _GridSystem_ folder in the root of your web app (~/GridSystem, not in ResourcePackages). This way the virtual file provider will find the template.
- of course, the path is also configurable and you can set it to a physical path (still relative to the web app but you won't have any problems pointing to a specific file). _Administration -> Settings -> Advanced -> Toolboxes -> Toolboxes -> PageLayouts -> Sections -> [Your package] -> Tools_: find your grid widget there and modify the _Layout Template_ field.

Yes, it would be better if sections for a specific package do not appear when a page is not using that particular package. This would require additional logic in the Sitefinity's page editor and that is outside of Feather's scope at the moment.

**Comment by tmsimont** [comment]
Hi Boyko,

I had a similar issue. Can you put some of your last comment onto the wiki about creating page [Page templates based on layout files with Feather](https://github.com/Sitefinity/feather/wiki/Page-templates-based-on-layout-files-with-Feather)?

It is not clear from reading that page that you need to manage your grid in this way, or that you can extend a package with that naming convention.

Is there more documentation available about the affects of the page layout naming?

**Comment by Boyko-Karadzhov** [comment]
Hello @tmsimont ,

In the first option we do not have a Layout file and the resource package is used on a custom page template. There is explanation in this article: [Feather Resource Packages](https://github.com/Sitefinity/feather/wiki/Feather-resource-packages) . It is in the "Utilize Frontend Packages" section in the wiki. Here the convention for naming page templates is specified.

The second option leverages the way our virtual file structure works. Here is the article: [VirtualFile structure explained](https://github.com/Sitefinity/feather/wiki/VirtualFile-structure-explained)

The third option just configures Sitefinity's toolbox. It has little to do with Feather itself.

I think the first article that I mentioned in this comment was the missing piece of the puzzle.

Regards,
Boyko

**Comment by tmsimont** [comment]
Thanks @Boyko-Karadzhov 

I actually misunderstood your comment. I thought you were saying that if I called my template /[My package]/MVC/Views/Layouts/[Other package Name].[Whatever] that I could then use the grid system from [other package name]

I thought that meant there was more to the naming convention of the templates than what is on the wiki. I see now that this is not the case.

**Comment by sitefinitysteve** [comment]
@Boyko-Karadzhov I tried changing the layoutTemplate for the items, but it just always changes itself back to ~/Frontend-Assembly/Telerik.Sitefinity.Frontend/GridSystem/ ?

**Comment by sitefinitysteve** [comment]
nm I just disabled that "auto" node and copy\pasted it to a new node

**Comment by sitefinitysteve** [comment]
This doesnt seem to work with the latest release

Resource Package called "Medportal"
Recycle
Templates and Layouts appear in the backend
Rename the existing masterpage from the SF UI to "Medportal.Root"
Load a page based on it, layout tab shows that convention
Any medportal layout USED however throws errors taht it cant find the cshtml for the layout
...and the widgets themselves also don't seem to be reading the markup from the resourcepackage.
