### ISSUE TITLE
A potentially dangerous Request.Path value was detected from the client (&).

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#1665]
Not sure where this is coming from...but clearly something is generating a gimped URL (this is from the log file)

05/11/2015 11:43:58
Type : System.Web.HttpException, System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Message : A potentially dangerous Request.Path value was detected from the client (&).
Source : System.Web
Help link : 
WebEventCode : 0
ErrorCode : -2147467259
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ValidateInputIfRequiredByConfig()
HResult : -2147467259
Stack Trace :    at System.Web.HttpRequest.ValidateInputIfRequiredByConfig()
   at System.Web.HttpApplication.PipelineStepManager.ValidateHelper(HttpContext context)

Additional Info:

MachineName : CLOUD-SERVER-03
TimeStamp : 5/11/2015 3:43:58 PM
FullName : Telerik.Sitefinity.Utilities, Version=8.0.5704.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/2/ROOT-1-130758146525568154
ThreadIdentity : 
WindowsIdentity : IIS APPPOOL\<POOL>
Requested URL : <SITE>/Telerik.Sitefinity.Frontend/Designer/View/DynamicContent/event=showWindow&winId=ctl00_ctl08_ctl00_ctl00_history&autoMax=false?controlId=e350fc73-5887-6d8b-9e8a-ff00003a1412&package=OutbreakHelp

**Comment by PepiIvanova** [comment]
Hi Steve,

We cannot reproduce the issue locally. Here is how we resolve template url when opening designers: 

var templatePath = String.format('Telerik.Sitefinity.Frontend/Designer/View/{0}/{1}?controlId={2}', widgetName, view, serverData.get('controlId'));

So the problem in your case is that the view is not correct: "event=showWindow&winId=ctl00_ctl08_ctl00_ctl00_history&autoMax=false" should be the name of the view.  Do you have any custom logic related to designers? Any additional information will be useful.

Best,
Pepi

**Comment by sitefinitysteve** [comment]
Nope, nothing custom....I have the project with support right now for a sitemap issue if someone needs the full thing
