### ISSUE TITLE
Error when trying to edit content block widget

### ISSUE THREAD

**Issue by veliniv** [Sitefinity/feather#2098]
Drag and drop Content Block widget and click Edit.

Following error is thrown in the console:
angular.js:11655 ReferenceError: ResourceNotFound is not defined
    at eval (eval at <anonymous> (http://localhost:8028/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Kendo/kendo.all.min.js:9:7189), <anonymous>:1:95)
    at n (http://localhost:8028/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Kendo/kendo.all.min.js:35:16632)
    at r.extend.render (http://localhost:8028/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Kendo/kendo.all.min.js:35:17129)
    at r.extend.bindTo (http://localhost:8028/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Kendo/kendo.all.min.js:35:14191)
    at new l.extend.init (http://localhost:8028/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Kendo/kendo.all.min.js:32:9212)
    at HTMLTextAreaElement.<anonymous> (http://localhost:8028/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Kendo/kendo.all.min.js:10:2045)
    at Function.m.extend.each (http://localhost:8028/ScriptResource.axd?d=kVF15MGzSN2BzrAWXum4pn1Cod7PCAyy…3u_SHxAUcMxYh587JCzbYI77uNhCTQfkiF3uXBE0n-0tUznDFGu0o5g2&t=566db134:2:2975)
    at m.fn.m.each (http://localhost:8028/ScriptResource.axd?d=kVF15MGzSN2BzrAWXum4pn1Cod7PCAyy…K3u_SHxAUcMxYh587JCzbYI77uNhCTQfkiF3uXBE0n-0tUznDFGu0o5g2&t=566db134:2:835)
    at mt.plugin.e.fn.(anonymous function) [as kendoEditor] (http://localhost:8028/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Kendo/kendo.all.min.js:10:2029)
    at d (http://localhost:8028/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Kendo/kendo.all.min.js:50:23752)

**Comment by ElenaGaneva** [comment]
Reproduced in gridDesigner branch and scrum2
