### ISSUE TITLE
Login Status : Error when submitting a registration

### ISSUE THREAD

**Issue by Sylvain-S** [Sitefinity/feather#2130]
On a page with the Registration and the LoginStatus widgets :

If you directly click on the submit button, 

Registration => Error messages are correctly displayed
Login Status => Exception occured while executing the controller. Check error logs for details.

Here is the error log:

Category: ErrorLog

Priority: 0

EventId: 9010

Severity: Warning

Title:Enterprise Library Exception Handling

Machine: PC-SYLVAIN

App Domain: /LM/W3SVC/11/ROOT-2-130804023038792746

ProcessId: 11176

Process Name: C:\Windows\SysWOW64\inetsrv\w3wp.exe

Thread Name: 

Win32 ThreadId:9684

Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 03/07/2015 13:07:37

Message: HandlingInstanceID: 2e8cd9e1-3bc2-4a2b-a533-93038852ab8c
An exception of type 'System.NullReferenceException' occurred and was caught.
-----------------------------------------------------------------------------
07/03/2015 15:07:37
Type : System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : Object reference not set to an instance of an object.
Source : Telerik.Sitefinity.Frontend.Identity
Help link : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void ValidateProfileData(Telerik.Sitefinity.Frontend.Identity.Mvc.Models.Profile.ProfileEditViewModel, System.Web.Mvc.ModelStateDictionary)
HResult : -2147467261
Stack Trace :    at Telerik.Sitefinity.Frontend.Identity.Mvc.Models.Profile.ProfileModel.ValidateProfileData(ProfileEditViewModel viewModel, ModelStateDictionary modelState)
   at Telerik.Sitefinity.Frontend.Identity.Mvc.Controllers.ProfileController.Index(ProfileEditViewModel viewModel)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass13.<InvokeActionMethodWithFilters>b__10()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass13.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass13.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass13.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass13.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass13.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
   at Telerik.Sitefinity.Mvc.ControllerWrapper.Execute()
   at Telerik.Sitefinity.Mvc.ControllerActionInvoker.ExecuteController(MvcProxyBase proxyControl)
   at Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Routing.DynamicUrlParamActionInvoker.ExecuteController(MvcProxyBase proxyControl)

Additional Info:

MachineName : PC-SYLVAIN
TimeStamp : 03/07/2015 13:07:37
FullName : Telerik.Sitefinity.Utilities, Version=8.0.5719.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/11/ROOT-2-130804023038792746
ThreadIdentity : 
WindowsIdentity : IIS APPPOOL\HubConstructor
Requested URL : http://hubconstructor.dev/bizcover/register/Index

Category: ErrorLog

Priority: 0

EventId: 9010

Severity: Warning

Title:Enterprise Library Exception Handling

Machine: PC-SYLVAIN

App Domain: /LM/W3SVC/11/ROOT-2-130804023038792746

ProcessId: 11176

Process Name: C:\Windows\SysWOW64\inetsrv\w3wp.exe

Thread Name: 

Win32 ThreadId:7548

Extended Properties: 
----------------------------------------

**Comment by Sylvain-S** [comment]
Better late than never ! Thanks anyway
