### ISSUE TITLE
modal-body breaks feather widgets' designer view

### ISSUE THREAD

**Issue by emtammaru** [Sitefinity/feather#2528]
I've replicated this issue in a fresh trial version of Sitefinity version 9.0.6010.0 and Feather version 1.5.490.0. 

Steps to reproduce:
1. Add `<div class="modal-body"></div>`  in any content block and Save.
2. Try to Edit any MVC widget.
3. The 'Save' 'Cancel', and 'Advanced' buttons are all gone from the Designer Modal.  

Here is the javascript error produced:

angular.min.js:102 Error: [ng:areq] http://errors.angularjs.org/1.3.15/ng/areq?p0=scope&p1=required
    at Error (native)
    at http://localhost:62601/Default/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:6:417
    at Rb (http://localhost:62601/Default/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:19:510)
    at http://localhost:62601/Default/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:50:35
    at link (http://localhost:62601/Default/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Designer/designer.js:110:62)
    at $ (http://localhost:62601/Default/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:70:197)
    at B (http://localhost:62601/Default/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:59:255)
    at g (http://localhost:62601/Default/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:51:335)
    at http://localhost:62601/Default/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:50:444
    at A.link (http://localhost:62601/Default/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular-route.min.js:7:408) `<script type="text/ng-template" section="modal-footer" class="ng-scope">`

**Comment by myriad7** [comment]
I confirm.  We have encountered the same issue in MVC widget templates.  The blue save button vanishes for the widget "edit" in the designer when the class="modal-body" is used.

**Comment by emtammaru** [comment]
@myriad7 This issue is resolved in Sitefinity 9.1.6100 and Feather 1.6.500.0.  Hope that helps you
