### ISSUE TITLE
Angular error while editing Image Widget - Sitefinity 9.2.6221 - Feather 1.7.6

### ISSUE THREAD

**Issue by shilpa835** [Sitefinity/feather#2641]
I am getting angular scripting errors while editing “image widget” in the latest release after upgrading to feather.
While editing an existing image, the select image modal window pops up instead of designer view window.

The angular errors are as follows 
Firefox error :

TypeError: Cannot read property 'Title' of undefined
    at r.$scope.hasErrors (designerview-simple.js?package=CUBootstrap:41)
    at fn0 (eval at compile (angular.js:13365), <anonymous>:4:441)
    at Object.get (angular.js:14345)
    at r.$digest (angular.js:15888)
    at angular.js:16091
    at e (angular.js:5552)
    at angular.js:5829

IE error :

The error is as follows :-
TypeError: Unable to get property 'Title' of undefined or null reference
   at $scope.hasErrors (http://localhost:8080/Frontend-Assembly/Telerik.Sitefinity.Frontend.Media/Mvc/Scripts/Image/designerview-simple.js?package=CUBootstrap:41:13)
   at fn0 (Function code:2:419)
   at Anonymous function (http://localhost:8080/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:114:415)
   at r.prototype.$digest (http://localhost:8080/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:131:6)
   at r.prototype.$apply (http://localhost:8080/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:134:76)
   at g (http://localhost:8080/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:87:442)
   at T (http://localhost:8080/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular.min.js:92:50)
   at w.onload (http://localhost:8080/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angula

Thanks,
Shilpa

**Comment by ElenaGaneva** [comment]
Hello Shilpa,

I can't reproduce this behavior in the latest version of 11.0 + (http://nuget.sitefinity.com/#/package/Telerik.Sitefinity.Feather.Core) .
If you still have the issue with latest versions please submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.

Regards,
Elena
